---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 288da920baedca3cb9ffd20e1f0c69201767e546
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: get-lead
  labels:
    expose: "true"
    app: i-ptg-test-get-lead
    provider: fabric8
    version: 0.1.0
    group: com.redhat
  name: i-ptg-test-get-lead
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: i-ptg-test-get-lead
    provider: fabric8
    group: com.redhat
