---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 288da920baedca3cb9ffd20e1f0c69201767e546
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: get-lead
    labels:
      expose: "true"
      app: i-ptg-test-get-lead
      provider: fabric8
      version: 0.1.0
      group: com.redhat
    name: i-ptg-test-get-lead
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: i-ptg-test-get-lead
      provider: fabric8
      group: com.redhat
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 288da920baedca3cb9ffd20e1f0c69201767e546
      fabric8.io/iconUrl: img/icons/camel.svg
      fabric8.io/git-branch: get-lead
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-ptg-test-get-lead&var-version=0.1.0
    labels:
      app: i-ptg-test-get-lead
      provider: fabric8
      version: 0.1.0
      group: com.redhat
    name: i-ptg-test-get-lead
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: i-ptg-test-get-lead
        provider: fabric8
        group: com.redhat
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 288da920baedca3cb9ffd20e1f0c69201767e546
          fabric8.io/iconUrl: img/icons/camel.svg
          fabric8.io/git-branch: get-lead
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=i-ptg-test-get-lead&var-version=0.1.0
        labels:
          app: i-ptg-test-get-lead
          provider: fabric8
          version: 0.1.0
          group: com.redhat
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: JAVA_APP_JAR
            value: i-ptg-test-get-lead-0.1.0.jar
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: i-ptg-test-get-lead:0.1.0
          imagePullPolicy: IfNotPresent
          name: i-ptg-test-get-lead
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8081
            name: sunproxyadmin
            protocol: TCP
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
